$(document).ready(function(){
        // $("#dash").show();
		$("#meminfo").hide();
        $("#attend").hide();
        $("#sched").hide();
        $("#salary").hide();
        $("#usersett").hide();
        $("#account").hide();
		$("#privacy").hide();
    
    $("#p1").click(function(){
       $("#dash").hide();
        $("#meminfo").show();
        $("#attend").hide();
        $("#sched").hide();
        $("#salary").hide();
        $("#usersett").hide();
        $("#account").hide();
        $("#privacy").hide();
    });
    $("#p2").click(function(){
        $("#dash").hide();
        $("#meminfo").hide();
        $("#attend").show();
        $("#sched").hide();
        $("#salary").hide();
        $("#usersett").hide();
        $("#account").hide();
        $("#privacy").hide();
    });
    $("#p3").click(function(){
        $("#dash").hide();
        $("#meminfo").hide();
        $("#attend").hide();
        $("#sched").show();
        $("#salary").hide();
        $("#usersett").hide();
        $("#account").hide();
        $("#privacy").hide();
    });
    $("#p4").click(function(){
        $("#dash").hide();
        $("#meminfo").hide();
        $("#attend").hide();
        $("#sched").hide();
        $("#salary").show();
        $("#usersett").hide();
        $("#account").hide();
        $("#privacy").hide();
    });
    $("#p5").click(function(){
        $("#dash").hide();
        $("#meminfo").hide();
        $("#attend").hide();
        $("#sched").hide();
        $("#salary").hide();
        $("#usersett").show();
        $("#account").hide();
        $("#privacy").hide();
    });
    $("#p6").click(function(){
        $("#dash").hide();
        $("#meminfo").hide();
        $("#attend").hide();
        $("#sched").hide();
        $("#salary").hide();
        $("#usersett").hide();
        $("#account").show();
        $("#privacy").hide();
    });
    $("#p7").click(function(){
        $("#dash").hide();
        $("#meminfo").hide();
        $("#attend").hide();
        $("#sched").hide();
        $("#salary").hide();
        $("#usersett").hide();
        $("#account").hide();
        $("#privacy").show();
    });
});